# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-30 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='favorite_is',
            field=models.BooleanField(default=False),
        ),
    ]
