# Generated by Django 2.0 on 2018-08-14 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20180806_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='favorite_is',
            field=models.BooleanField(default=False),
        ),
    ]
