# Generated by Django 2.0 on 2018-08-15 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_album_favorite_is'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='favorite_is',
        ),
    ]
