# Generated by Django 2.0 on 2018-08-15 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_remove_album_favorite_is'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='favorite_is',
            field=models.BooleanField(default=False),
        ),
    ]
